---
title: "Replication of Racial Progress as Threat to the Status Hierarhcy: Implications for Perceptions of Anti-White Bias by Wilkins & Kaiser (2014, Psychological Science)"
author: "Ellen Reinhart (ereinhar@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

###Original Paper
[Wilkins, C. L., & Kaiser, C. R. (2014). Racial progress as threat to the status hierarchy: Implications for perceptions of anti-White bias. *Psychological Science, 25*(2). https://doi.org/10.1177/0956797613508412](https://github.com/ecreinhart/wilkins2014/blob/master/original_paper/wilkins_kaiser_2014.pdf)

###Repository
[Wilkins & Kaiser (2014) study 2 replication](https://github.com/ecreinhart/wilkins2014)

###Justification

In my research program, I aim to understand how perceptions of inequality impact support for equality-promoting policies. The primary goal of my research is to understand how those with high status and in positions of power perceive inequality and become motivated to address it rather than perpetuate unjust hierarchies. Wilkins and Kaiser (2014) found that priming White participants with racial progress threatened those who strongly support the status quo, causing them to cite more anti-White bias compared to participants who do not support the status quo or who were not primed with racial progress. 

Replicating study 2 of Wilkins and Kiaser's study will provide me with the opportunity to use mock newspaper articles to manipulate perceptions of inequality and to use well-established scales for measuring status-legitimizing beliefs (Levin et al., 1998). Using this paradigm relates to my first year project, in which I intend to conduct a cross-cultural comparison of the relationship between perceived inequality and motivation to take social action. I hypothesize that cultural differences in status-legitimizing beliefs will impact perceptions of inequality and motivation to take social action. To test this hypothesis, I will manipulate perceptions of inequality, using a similar paradigm to Wilkins and Kaiser's study. 


##Methods

White participants will be recruited from Amazon Mechanical Turk and randomly assigned to one of two conditions: 1) racial progress or 2) control. In the racial progress condition, participants will read a news article about racial minorities in high-status positions. In the control condition, participants will read a news article about a low-ranked swim team winning a championship. After reading the article, participants will complete measures of racial progress, system-legitimizing beliefs, anti-White bias, and demographics. Wilkins posted the racial progres and control news articles on her personal website along with the exact wording and formatting of the measures used in the study ([see reserach materials here](http://silab.research.wesleyan.edu/research-materials/), which will allow for a very close replication. 

###Challenges 

I am familiar with Qualtircs and confident I can execute the study protocol. The news articles will need to be updated (e.g., article publication date, date by which race may not be a marker of status in the United States), but the content will remain the same.  One important change to note is that the sociopolitical climate has changed since the original study was run in 2014, which may impaact the results of the replciation. Regardless of whether the results replicate, the outcome will be informative. 

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
